### ISSUE TITLE
Param Error During Init

### ISSUE THREAD

**Issue by eethann** [sixolet/matrix#1]
I'm super excited for the matrix mod, and the new UI looks awesome. It also reduced the line count for the K2000 style funs by a bunch.

That said, I'm not able to run it on my norns shield yet. I'm getting the following error - 

```
# script clear
calling: toolkit post clean
calling: clear the matrix for the next script
lua: /home/we/norns/lua/core/paramset.lua:118: attempt to compare string with number
stack traceback:
	/home/we/norns/lua/core/paramset.lua:118: in function 'core/paramset.add_group'
	/home/we/norns/lua/core/audio.lua:258: in function 'core/audio.add_params'
	/home/we/norns/lua/core/script.lua:98: in function 'core/script.clear'
	/home/we/norns/lua/core/script.lua:159: in function 'core/script.load'
	/home/we/norns/lua/core/menu/preview.lua:23: in function 'core/menu/preview.key'
	/home/we/norns/lua/core/menu.lua:143: in function </home/we/norns/lua/core/menu.lua:120>
```

I at first thought it was my code, but commented all that out and am still getting it.

Starting this thread here, curious if you have any ideas, and I'll also try to take a look when I have a moment.

Thanks!

**Comment by sixolet** [comment]
What script are you running it with?

**Comment by eethann** [comment]
Awake

**Comment by sixolet** [comment]
Update and try again, I think I fixed it this morning.

**Comment by eethann** [comment]
Indeed, that worked!
